-- Gerado por scripts/generate-supabase-schema.js. Não editar manualmente.

-- Fonte: src/main/database/migrations.ts

create schema if not exists public;

CREATE TABLE empresas (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome        TEXT    NOT NULL,
      cnpj        TEXT,
      email       TEXT,
      telefone    TEXT,
      endereco    TEXT,
      logo        TEXT,
      ativo       BIGINT NOT NULL DEFAULT 1,
      created_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    , solicitante_padrao    TEXT, autorizado_por_padrao TEXT, cidade TEXT, estado TEXT, logo_url TEXT, razao_social TEXT, titulo_obra TEXT);

CREATE TABLE contas (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome        TEXT    NOT NULL,
      tipo        TEXT    NOT NULL DEFAULT 'corrente',
      banco       TEXT,
      agencia     TEXT,
      numero      TEXT,
      saldo       NUMERIC    NOT NULL DEFAULT 0,
      ativo       BIGINT NOT NULL DEFAULT 1,
      empresa_id  BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      created_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE categorias (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome        TEXT    NOT NULL,
      tipo        TEXT    NOT NULL DEFAULT 'ambos',
      cor         TEXT    NOT NULL DEFAULT '#6366f1',
      descricao   TEXT,
      ativo       BIGINT NOT NULL DEFAULT 1,
      empresa_id  BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      created_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE clientes (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome        TEXT    NOT NULL,
      cpf_cnpj    TEXT,
      email       TEXT,
      telefone    TEXT,
      endereco    TEXT,
      tipo        TEXT    NOT NULL DEFAULT 'pj',
      ativo       BIGINT NOT NULL DEFAULT 1,
      empresa_id  BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      created_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE fornecedores (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome        TEXT    NOT NULL,
      cpf_cnpj    TEXT,
      email       TEXT,
      telefone    TEXT,
      endereco    TEXT,
      categoria   TEXT,
      ativo       BIGINT NOT NULL DEFAULT 1,
      empresa_id  BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      created_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    , tipo_pessoa TEXT NOT NULL DEFAULT 'pj', cnpj TEXT, cpf TEXT, forma_pagamento TEXT NOT NULL DEFAULT 'boleto', banco TEXT, agencia TEXT, operacao TEXT, conta TEXT, conta_digito TEXT, tipo_conta TEXT, chave_pix TEXT);

CREATE TABLE lancamentos (
      id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      descricao      TEXT    NOT NULL,
      tipo           TEXT    NOT NULL CHECK(tipo IN ('receita','despesa')),
      valor          NUMERIC    NOT NULL CHECK(valor > 0),
      data_venc      TEXT    NOT NULL,
      data_pgto      TEXT,
      status         TEXT    NOT NULL DEFAULT 'pendente'
                             CHECK(status IN ('pendente','pago','cancelado')),
      observacao     TEXT,
      conta_id       BIGINT REFERENCES contas(id)      ON DELETE SET NULL,
      categoria_id   BIGINT REFERENCES categorias(id)  ON DELETE SET NULL,
      cliente_id     BIGINT REFERENCES clientes(id)    ON DELETE SET NULL,
      fornecedor_id  BIGINT REFERENCES fornecedores(id) ON DELETE SET NULL,
      empresa_id     BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      created_at     TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    , data TEXT);

CREATE TABLE configuracoes (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      chave       TEXT    NOT NULL,
      valor       TEXT,
      empresa_id  BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
      UNIQUE(chave, empresa_id)
    );

CREATE TABLE anexos (
      id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      lancamento_id  BIGINT NOT NULL REFERENCES lancamentos(id) ON DELETE CASCADE,
      nome           TEXT    NOT NULL,
      caminho        TEXT    NOT NULL,
      tamanho        BIGINT,
      mime           TEXT,
      created_at     TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE auditoria (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tabela      TEXT    NOT NULL,
      registro_id BIGINT NOT NULL,
      acao        TEXT    NOT NULL CHECK(acao IN ('insert','update','delete')),
      dados_antes TEXT,
      dados_depois TEXT,
      empresa_id  BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
      created_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE colaboradores (
      id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id                    BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,

      -- Identificação
      nome                          TEXT    NOT NULL,
      cpf                           TEXT,
      rg                            TEXT,
      rg_orgao_emissor              TEXT,
      nascimento                    TEXT,
      estado_civil                  TEXT,
      nacionalidade                 TEXT    DEFAULT 'Brasileira',
      nome_mae                      TEXT,
      nome_pai                      TEXT,
      escolaridade                  TEXT,
      pcd                           BIGINT NOT NULL DEFAULT 0,
      foto_url                      TEXT,

      -- Contrato
      funcao                        TEXT,
      setor                         TEXT,
      equipe                        TEXT,
      tipo_contrato                 TEXT    DEFAULT 'CLT',
      data_admissao                 TEXT,
      dias_experiencia              BIGINT DEFAULT 45,
      data_vencimento_experiencia   TEXT,
      data_demissao                 TEXT,
      tipo_demissao                 TEXT,
      salario_base                  NUMERIC,
      status                        TEXT    NOT NULL DEFAULT 'ativo'
                                             CHECK(status IN ('ativo','afastado','ferias','desligado')),

      -- Documentos trabalhistas
      ctps                          TEXT,
      ctps_serie                    TEXT,
      pis                           TEXT,

      -- Contato
      telefone                      TEXT,
      email                         TEXT,
      contato_emergencia_nome       TEXT,
      contato_emergencia_telefone   TEXT,

      -- Endereço
      endereco                      TEXT,
      numero                        TEXT,
      bairro                        TEXT,
      cidade                        TEXT,
      estado                        TEXT,
      cep                           TEXT,

      -- Dados bancários
      banco                         TEXT,
      agencia                       TEXT,
      operacao                      TEXT,
      conta                         TEXT,
      conta_digito                  TEXT,
      tipo_conta                    TEXT,

      -- Benefícios / viagem
      passagem                      TEXT,
      valor_ida_volta               NUMERIC,
      alimentacao                   NUMERIC,

      -- Uniforme / EPI
      tamanho_camisa                TEXT,
      tamanho_calca                 TEXT,
      numero_calcado                TEXT,

      observacoes                   TEXT,
      created_at                    TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    , titulo_numero TEXT, titulo_zona TEXT, titulo_secao TEXT, reservista TEXT, cnh_numero TEXT, cnh_categoria TEXT, cnh_vencimento TEXT, cor_raca TEXT, alojado BIGINT NOT NULL DEFAULT 0, tem_baixada BIGINT NOT NULL DEFAULT 0, matricula_esocial TEXT, sexo TEXT, naturalidade TEXT, cbo TEXT, rg_data_emissao TEXT, ctps_data_expedicao TEXT, ctps_uf TEXT);

CREATE TABLE colaborador_documentos (
      id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      colaborador_id BIGINT NOT NULL REFERENCES colaboradores(id) ON DELETE CASCADE,
      empresa_id     BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      tipo           TEXT    NOT NULL,
      dados_json      TEXT,
      created_at     TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE recibos (
      id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id         BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      beneficiario_nome  TEXT    NOT NULL,
      valor              NUMERIC    NOT NULL,
      referente          TEXT,
      created_at         TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE opcoes_colaborador (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id  BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      tipo        TEXT    NOT NULL CHECK(tipo IN ('funcao','setor','equipe')),
      nome        TEXT    NOT NULL,
      ativo       BIGINT NOT NULL DEFAULT 1,
      created_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      UNIQUE(empresa_id, tipo, nome)
    );

CREATE TABLE produtos (
      id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id      BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      codigo          TEXT    NOT NULL,
      nome            TEXT    NOT NULL,
      descricao       TEXT,
      unidade         TEXT,
      estoque_atual   NUMERIC    NOT NULL DEFAULT 0,
      estoque_minimo  NUMERIC    NOT NULL DEFAULT 0,
      valor_unitario  NUMERIC    NOT NULL DEFAULT 0,
      created_at      TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    , fornecedor_id BIGINT REFERENCES fornecedores(id), alugado BIGINT NOT NULL DEFAULT 0, valor_aluguel NUMERIC, aluguel_periodo TEXT, aluguel_vencimento TEXT);

CREATE TABLE almoxarifado_entradas (
      id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id       BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      numero_nota      TEXT,
      numero_pedido    TEXT,
      data             TEXT    NOT NULL,
      fornecedor_id    BIGINT REFERENCES fornecedores(id) ON DELETE SET NULL,
      fornecedor_nome  TEXT    NOT NULL,
      valor_desconto   NUMERIC    NOT NULL DEFAULT 0,
      valor_total      NUMERIC    NOT NULL DEFAULT 0,
      lancamento_id    BIGINT REFERENCES lancamentos(id) ON DELETE SET NULL,
      created_at       TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE almoxarifado_entradas_itens (
      id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      entrada_id      BIGINT NOT NULL REFERENCES almoxarifado_entradas(id) ON DELETE CASCADE,
      produto_id      BIGINT NOT NULL REFERENCES produtos(id),
      produto_codigo  TEXT    NOT NULL,
      produto_nome    TEXT    NOT NULL,
      quantidade      NUMERIC    NOT NULL,
      valor_unitario  NUMERIC    NOT NULL,
      valor_total     NUMERIC    NOT NULL
    );

CREATE TABLE pessoas_avulsas (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id  BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      nome        TEXT    NOT NULL,
      cpf         TEXT,
      created_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE almoxarifado_saidas (
      id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id          BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      data                TEXT    NOT NULL,
      produto_id          BIGINT NOT NULL REFERENCES produtos(id),
      produto_codigo      TEXT    NOT NULL,
      produto_nome        TEXT    NOT NULL,
      quantidade          NUMERIC    NOT NULL,
      retirado_por_tipo   TEXT    NOT NULL DEFAULT 'colaborador',
      retirado_por_id     BIGINT,
      retirado_por_nome   TEXT    NOT NULL,
      setor               TEXT,
      solicitado_por_id   BIGINT REFERENCES colaboradores(id) ON DELETE SET NULL,
      solicitado_por_nome TEXT,
      liberado_por        TEXT,
      pdf_path            TEXT,
      created_at          TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE notificacoes_eventos (
      id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id            BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      tipo                  TEXT    NOT NULL,
      destinatario_perfil   TEXT    NOT NULL,
      titulo                TEXT    NOT NULL,
      mensagem              TEXT,
      lida                  BIGINT NOT NULL DEFAULT 0,
      created_at            TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    , referencia_id BIGINT);

CREATE TABLE lotes_financeiros (
      id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id   BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      titulo       TEXT    NOT NULL,
      data_inicio  TEXT    NOT NULL,
      data_fim     TEXT    NOT NULL,
      criado_por   TEXT,
      created_at   TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    , enviado_em TEXT, numero BIGINT);

CREATE TABLE "usuarios" (
      id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id     BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      nome           TEXT    NOT NULL,
      email          TEXT    NOT NULL,
      senha_hash     TEXT    NOT NULL,
      perfil         TEXT    NOT NULL DEFAULT 'gestor'
                             CHECK(perfil IN ('admin','gestor','almoxarife','supervisor','central','master','setor_pessoal')),
      ativo          BIGINT NOT NULL DEFAULT 1,
      created_at     TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      last_login_at  TEXT, carimbo_url TEXT,
      UNIQUE(email, empresa_id)
    );

CREATE TABLE autorizacoes_pagamento (
      id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id          BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,

      beneficiario_tipo   TEXT    NOT NULL CHECK(beneficiario_tipo IN ('fornecedor','colaborador')),
      beneficiario_id     BIGINT NOT NULL,
      beneficiario_nome   TEXT    NOT NULL,

      descricao           TEXT,
      valor               NUMERIC    NOT NULL,
      observacoes         TEXT,
      vencimento          TEXT,
      solicitante         TEXT,
      autorizado_por      TEXT,

      created_at          TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    , lancamento_id BIGINT REFERENCES lancamentos(id) ON DELETE SET NULL, pdf_path TEXT, aprovado_por TEXT, aprovado_em TEXT, lote_id BIGINT REFERENCES lotes_financeiros(id) ON DELETE SET NULL, aprovado_supervisor_por TEXT, aprovado_supervisor_em TEXT, aprovado_central_por TEXT, aprovado_central_em TEXT, aprovado_por_usuario_id BIGINT REFERENCES usuarios(id), aprovado_supervisor_por_usuario_id BIGINT REFERENCES usuarios(id));

CREATE TABLE notas_fiscais (
      id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id       BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      numero_pedido    TEXT,
      data             TEXT    NOT NULL,
      numero_nf        TEXT,
      fornecedor_id    BIGINT REFERENCES fornecedores(id) ON DELETE SET NULL,
      fornecedor_nome  TEXT    NOT NULL,
      lancamento_id    BIGINT REFERENCES lancamentos(id)  ON DELETE SET NULL,
      created_at       TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    , nota_pdf_path TEXT, boletos_pdf_path TEXT, aprovado_por TEXT, aprovado_em TEXT, lote_id BIGINT REFERENCES lotes_financeiros(id) ON DELETE SET NULL, aprovado_supervisor_por TEXT, aprovado_supervisor_em TEXT, aprovado_central_por TEXT, aprovado_central_em TEXT, data_emissao_nf TEXT, aprovado_por_usuario_id BIGINT REFERENCES usuarios(id), aprovado_supervisor_por_usuario_id BIGINT REFERENCES usuarios(id));

CREATE TABLE notas_fiscais_boletos (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nota_id     BIGINT NOT NULL REFERENCES notas_fiscais(id) ON DELETE CASCADE,
      valor       NUMERIC    NOT NULL,
      vencimento  TEXT    NOT NULL
    , lancamento_id BIGINT REFERENCES lancamentos(id) ON DELETE SET NULL);

CREATE TABLE autorizacoes_pagamento_boletos (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ap_id       BIGINT NOT NULL REFERENCES autorizacoes_pagamento(id) ON DELETE CASCADE,
      valor       NUMERIC    NOT NULL,
      vencimento  TEXT    NOT NULL
    , lancamento_id BIGINT REFERENCES lancamentos(id) ON DELETE SET NULL);

CREATE TABLE autorizacoes_pagamento_anexos (
      id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      ap_id    BIGINT NOT NULL REFERENCES autorizacoes_pagamento(id) ON DELETE CASCADE,
      caminho  TEXT    NOT NULL,
      ordem    BIGINT NOT NULL
    );

CREATE TABLE usuario_permissoes_extras (
      id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      usuario_id   BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
      chave        TEXT    NOT NULL, negada BIGINT NOT NULL DEFAULT 0,
      UNIQUE(usuario_id, chave)
    );

CREATE TABLE notas_fiscais_anexos (
      id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nota_id   BIGINT NOT NULL REFERENCES notas_fiscais(id) ON DELETE CASCADE,
      caminho   TEXT    NOT NULL,
      categoria TEXT    NOT NULL CHECK(categoria IN ('nota','boleto')),
      ordem     BIGINT NOT NULL
    );

CREATE TABLE supervisor_obras (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      usuario_id  BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
      empresa_id  BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      UNIQUE(usuario_id, empresa_id)
    );

CREATE TABLE usuario_obras (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      usuario_id  BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
      empresa_id  BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      UNIQUE(usuario_id, empresa_id)
    );

CREATE TABLE solicitacoes_pessoal (
      id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      empresa_id          BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
      colaborador_id      BIGINT NOT NULL REFERENCES colaboradores(id) ON DELETE CASCADE,
      tipo                TEXT    NOT NULL CHECK(tipo IN ('admissao','desligamento','alteracao_salarial','outro')),
      status              TEXT    NOT NULL DEFAULT 'pendente' CHECK(status IN ('pendente','respondido','concluido')),
      observacoes         TEXT,
      solicitado_por      TEXT    NOT NULL,
      solicitado_em       TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      resposta_observacoes TEXT,
      respondido_por      TEXT,
      respondido_em       TEXT,
      concluido_em        TEXT
    );

CREATE TABLE solicitacoes_pessoal_anexos (
      id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      solicitacao_id  BIGINT NOT NULL REFERENCES solicitacoes_pessoal(id) ON DELETE CASCADE,
      caminho         TEXT    NOT NULL,
      nome            TEXT    NOT NULL,
      origem          TEXT    NOT NULL CHECK(origem IN ('adm','setor_pessoal')),
      ordem           BIGINT NOT NULL DEFAULT 0,
      created_at      TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE colaboradores_anexos (
      id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      colaborador_id  BIGINT NOT NULL REFERENCES colaboradores(id) ON DELETE CASCADE,
      caminho         TEXT    NOT NULL,
      nome            TEXT    NOT NULL,
      descricao       TEXT,
      created_at      TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE recuperacao_senha (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      usuario_id  BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
      codigo      TEXT    NOT NULL,
      expira_em   TEXT    NOT NULL,
      usado       BIGINT NOT NULL DEFAULT 0,
      created_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

CREATE TABLE configuracoes_email (
      id               BIGINT PRIMARY KEY CHECK (id = 1),
      smtp_host        TEXT,
      smtp_porta       BIGINT,
      smtp_usuario     TEXT,
      smtp_senha       TEXT,
      smtp_seguro      BIGINT NOT NULL DEFAULT 1,
      remetente_nome   TEXT,
      remetente_email  TEXT,
      updated_at       TEXT
    );

CREATE INDEX idx_lanc_empresa
      ON lancamentos(empresa_id);

CREATE INDEX idx_lanc_status
      ON lancamentos(status);

CREATE INDEX idx_lanc_tipo
      ON lancamentos(tipo);

CREATE INDEX idx_lanc_data_venc
      ON lancamentos(data_venc);

CREATE INDEX idx_lanc_conta
      ON lancamentos(conta_id);

CREATE INDEX idx_lanc_categoria
      ON lancamentos(categoria_id);

CREATE INDEX idx_contas_empresa
      ON contas(empresa_id);

CREATE INDEX idx_categorias_empresa
      ON categorias(empresa_id);

CREATE INDEX idx_clientes_empresa
      ON clientes(empresa_id);

CREATE INDEX idx_fornecedores_empresa
      ON fornecedores(empresa_id);

CREATE INDEX idx_anexos_lancamento
      ON anexos(lancamento_id);

CREATE INDEX idx_auditoria_tabela
      ON auditoria(tabela, registro_id);

CREATE INDEX idx_auditoria_empresa
      ON auditoria(empresa_id);

CREATE INDEX idx_colaboradores_empresa
      ON colaboradores(empresa_id);

CREATE INDEX idx_colaboradores_status
      ON colaboradores(status);

CREATE INDEX idx_colaboradores_funcao
      ON colaboradores(funcao);

CREATE INDEX idx_colab_documentos_colaborador
      ON colaborador_documentos(colaborador_id);

CREATE INDEX idx_ap_empresa
      ON autorizacoes_pagamento(empresa_id);

CREATE INDEX idx_ap_beneficiario
      ON autorizacoes_pagamento(beneficiario_tipo, beneficiario_id);

CREATE INDEX idx_recibos_empresa
      ON recibos(empresa_id);

CREATE INDEX idx_opcoes_colaborador_busca
      ON opcoes_colaborador(empresa_id, tipo);

CREATE INDEX idx_notas_fiscais_empresa
      ON notas_fiscais(empresa_id);

CREATE INDEX idx_notas_fiscais_boletos_nota
      ON notas_fiscais_boletos(nota_id);

CREATE INDEX idx_ap_boletos_ap
      ON autorizacoes_pagamento_boletos(ap_id);

CREATE INDEX idx_ap_anexos_ap
      ON autorizacoes_pagamento_anexos(ap_id);

CREATE INDEX idx_produtos_empresa
      ON produtos(empresa_id);

CREATE INDEX idx_almox_entradas_empresa
      ON almoxarifado_entradas(empresa_id);

CREATE INDEX idx_almox_entradas_itens_entrada
      ON almoxarifado_entradas_itens(entrada_id);

CREATE INDEX idx_pessoas_avulsas_empresa
      ON pessoas_avulsas(empresa_id);

CREATE INDEX idx_almox_saidas_empresa
      ON almoxarifado_saidas(empresa_id);

CREATE INDEX idx_usuario_permissoes_extras_usuario
      ON usuario_permissoes_extras(usuario_id);

CREATE INDEX idx_notificacoes_eventos_busca
      ON notificacoes_eventos(empresa_id, destinatario_perfil, lida);

CREATE INDEX idx_nf_anexos_nota
      ON notas_fiscais_anexos(nota_id);

CREATE INDEX idx_supervisor_obras_usuario
      ON supervisor_obras(usuario_id);

CREATE INDEX idx_supervisor_obras_empresa
      ON supervisor_obras(empresa_id);

CREATE INDEX idx_lotes_financeiros_empresa
      ON lotes_financeiros(empresa_id);

CREATE INDEX idx_usuario_obras_usuario
      ON usuario_obras(usuario_id);

CREATE INDEX idx_usuario_obras_empresa
      ON usuario_obras(empresa_id);

CREATE INDEX idx_usuarios_empresa
      ON usuarios(empresa_id);

CREATE INDEX idx_solicitacoes_pessoal_empresa
      ON solicitacoes_pessoal(empresa_id);

CREATE INDEX idx_solicitacoes_pessoal_colaborador
      ON solicitacoes_pessoal(colaborador_id);

CREATE INDEX idx_solicitacoes_pessoal_status
      ON solicitacoes_pessoal(status);

CREATE INDEX idx_solic_pessoal_anexos_solicitacao
      ON solicitacoes_pessoal_anexos(solicitacao_id);

CREATE INDEX idx_colaboradores_anexos_colaborador
      ON colaboradores_anexos(colaborador_id);

CREATE INDEX idx_recuperacao_senha_usuario
      ON recuperacao_senha(usuario_id);

